### ISSUE TITLE
Custom card integration example

### ISSUE THREAD

**Issue by mario-vuckovic** [adyen-examples/adyen-react-native-online-payments#3]
Hi, thanks for offering examples for React native :)

In Adyen documentation there's an example for iOS/Android covering Custom card integration which consists of:
- Building your own payment form
- Using Adyen core library to encrypt card data
- Sending encrypted data to server (which will send it to Adyen server)

1. Would it be possible to implement this flow in React Native as well?
2. Would PCI Compliance stay the same (it's currently unspecified in docs)?
3. Would the solution have to use native library + RN bridge or it's possible to use pure Javascript to encrypt the data?

Thanks in advance.

**Comment by deepu105** [comment]
Hi could you provide the link of the doc (xample for iOS/Android covering Custom card integration) you are referring to

**Comment by mario-vuckovic** [comment]
> Hi could you provide the link of the doc (xample for iOS/Android covering Custom card integration) you are referring to

- Custom Cards Docs page: https://docs.adyen.com/payment-methods/cards/custom-card-integration
- iOS section: https://docs.adyen.com/payment-methods/cards/custom-card-integration?tab=i_os_2
- Android Section: https://docs.adyen.com/payment-methods/cards/custom-card-integration?tab=android_3

Kind regards

**Comment by deepu105** [comment]
You should be able to use a similar approach but pure JS solution won't be possible at the moment. We do have plans to build a React Native component next year but for now your best bet is to use the Android and IOS adyen libs and create a RN binding for them
